import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';
import Provider from './provider';
import { Locale } from '../../types/locale';
import { AbstractIntlMessages, NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import AppProvider from '../../components/appProvider';

const myFont = localFont({
  src: [
    {
      path: '../../../public/fonts/Shubbak-Medium.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/Shubbak-Bold.woff',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-shubbak',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: Locale };
}) {
  const messages: AbstractIntlMessages = await getMessages();
  let { locale } = await params;
  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body className={`${myFont.className}  antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <Provider>
            <AppProvider>{children}</AppProvider>
          </Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
